version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "01:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: husky
    versions:
    - 4.3.6
    - 4.3.8
  - dependency-name: "@types/node"
    versions:
    - 14.14.17
    - 14.14.22
  - dependency-name: nock
    versions:
    - 13.0.5
    - 13.0.7
  - dependency-name: make-fetch-happen
    versions:
    - 8.0.12
    - 8.0.13
  - dependency-name: standard-version
    versions:
    - 9.1.0
  - dependency-name: "@types/jest"
    versions:
    - 26.0.19
  - dependency-name: typescript
    versions:
    - 3.9.7
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
